### ISSUE TITLE
what is the performance of your mode implementation?

### ISSUE THREAD

**Issue by semchan** [yiskw713/video_feature_extractor#2]
Thanks for your contribution！ But may I know what is your performance results of your released mode? thanks a lot.

**Comment by yiskw713** [comment]
Hi semchan,

Thank you for visiting my repository and sorry for the delay in replying.
Actually, I lost the result file in Kinetics 700 validation set and I do not have enough resources to measure the accuracy now.
I think the top1 accuracies of both models are 50% ~ 60%.
If you can wait for a month or longer, I can tell you the exact performances.

Best regards,
