### ISSUE TITLE
help testing the code

### ISSUE THREAD

**Issue by hayachiq** [yiskw713/video_feature_extractor#4]
hi, ;) I have downloaded MSR-VTT and need to get the videos features 
can you please me help me how to run the code to get the features for the videos

**Comment by yiskw713** [comment]
@hayachiq Hi,

To get the features of MSR-VTT videos, please do the following
1. Convert the mp4 videos to hdf5 ()
2. Make the csv file containing the video name and the number of frames like `csv/msr-vtt.csv`
3. Downlod pre-trained models from [here](https://github.com/kenshohara/3D-ResNets-PyTorch).
    (Sorry, my link in README.md is not available)
4. Run `python extract.py`

**Comment by hayachiq** [comment]
thank you for your help it works correctly only needed bellow changes on windows without gpu:
1- model.load_state_dict(state_dict, strict=False)  
2- change from cuda to cpu in serialization.py
3-  video_path = 'path'+name+'.hdf5'
